name: Build and Test BML WPF App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.413

    - name: Restore dependencies
      run: dotnet restore BML/BML.csproj

    - name: Build and test
      run: |
        dotnet build BML/BML.csproj
        dotnet test BML.Tests/BML.Tests.csproj
